export const CHECK_LOGIN = "CHECK_LOGIN";
export const LOGIN_SUCCESSFUL = 'LOGIN'
export const REGISTER_SUCCESSFUL='REGISTER'
export const LOGOUT_SUCCESSFUL = 'LOGOUT';
export const GET_ERROR = 'GETERROR';
export const CLEAR_ERROR = 'CLEARERROR'
export const USER_LOADING = 'USERLOADING';
export const USER_LOADED = 'USERLOADED';
export const AUTH_ERROR = 'AUTHERROR'
